version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: scraper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
